version: "3"

dotenv:
  - .env

tasks:
  format:
    desc: Format source code
    cmds:
      - gofmt -w .

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  dev:
    desc: Run the development app with hot-reload
    cmds:
      - air

  build:
    desc: Build the API binary
    cmds:
      - go build -o ./bin/api.exe ./cmd/api

  migration-up:
    desc: "run database up migrations"
    cmds:
      - migrate -path ./db/migrations -database "{{.DATABASE_URL}}" up

  migrate-down:
    desc: Roll back one migration
    cmds:
      - migrate -path ./db/migrations -database "{{.DATABASE_URL}}" down 1

  migrate-create:
    desc: Create new database migration
    cmds:
      - migrate create -ext sql -dir ./db/migrations {{.CLI_ARGS}}
